#########
##  ============LICENSE_START====================================================
##  org.onap.aaf
##  ===========================================================================
##  Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
##  ===========================================================================
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##  ============LICENSE_END====================================================
##
###
### AAF-GUI
###
kind: Service
apiVersion: v1
metadata:
  name: aaf-gui
spec:
  selector:
    app: aaf-gui
  type: NodePort
  ports:
    - name: aaf-gui
      protocol: TCP
      nodePort: 30083
      port: 8200
      targetPort: 8200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaf-gui
  labels:
    app: aaf-gui
spec:
  replicas: {{ .Values.replicas.gui }}
  selector:
    matchLabels:
      app: aaf-gui
  template:
    metadata:
      labels:
        app: aaf-gui
    spec:
      volumes:
        # Use this Pod Sharing dir to declare various States of starting
      - name: {{ .Chart.Name }}-config-vol
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-config-pvc
      - name: {{ .Chart.Name }}-status-vol
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-status-pvc
      initContainers:
        - name: {{ .Chart.Name }}-config-container
          image: {{ .Values.image.repository }}onap/aaf/aaf_config:{{ .Values.image.version }}
          imagePullPolicy: IfNotPresent
          command: ["bash","/opt/app/aaf_config/bin/agent.sh"]
          volumeMounts:
            - mountPath: "/opt/app/osaaf"
              name: {{ .Chart.Name }}-config-vol
          env:
            - name: AAF_ENV
              value: "{{ .Values.cadi.aaf_env }}"
            - name: LATITUDE
              value: "{{ .Values.cadi.cadi_latitude }}"
            - name: LONGITUDE
              value: "{{ .Values.cadi.cadi_longitude }}"
            - name: aaf_locator_container
              value: "helm"
            - name: aaf_locator_container_ns
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: aaf_locate_url
              value: "https://aaf-locate.onap:8095"
            - name: aaf_locator_public_fqdn
              value: "aaf.osaaf.org"
            - name: CASSANDRA_CLUSTER
              value: "aaf-cass"
#            - name: CASSANDRA_USER
#              value: ""
#            - name: CASSANDRA_PASSWORD
#              value: ""
#           - name: CASSANDRA_PORT
#              value: ""
      containers:
###
### AAF-GUI
###
      - name: {{ .Chart.Name }}-gui
        image: {{ .Values.image.repository }}onap/aaf/aaf_gui:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","-c","cd /opt/app/aaf && /bin/bash bin/pod_wait.sh aaf-gui aaf-locate && exec bin/gui"]
        volumeMounts:
        -  mountPath: "/opt/app/osaaf"
           name: {{ .Chart.Name }}-config-vol
        -  mountPath: "/opt/app/aaf/status"
           name: {{ .Chart.Name }}-status-vol
        ports:
        - name: aaf-gui
          protocol: TCP
          containerPort: 8200


