#########
##  ============LICENSE_START====================================================
##  org.onap.aaf
##  ===========================================================================
##  Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
##  ===========================================================================
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##  ============LICENSE_END====================================================
##
###
### AAF-HELLO
###
kind: Service
apiVersion: v1
metadata:
  name: aaf-hello
spec:
  selector:
    app: aaf-hello
  type: NodePort
  ports:
    - name: aaf-hello
      protocol: TCP
      port: {{.Values.cadi.port}}
      nodePort: {{ .Values.cadi.public_port}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaf-hello
  labels:
    app: aaf-hello
spec:
  replicas: {{ .Values.replicas.hello }}
  selector:
    matchLabels:
      app: aaf-hello
  template:
    metadata:
      labels:
        app: aaf-hello
    spec:
      volumes:
        # Use this Pod Sharing dir to declare various States of starting
      - name: aaf-hello-vol
        emptyDir: {}
      initContainers:
        - name: aaf-hello-config
          image: {{ .Values.image.repository }}onap/aaf/aaf_agent:{{ .Values.image.version }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/opt/app/osaaf/local"
              name: aaf-hello-vol
          command: ["bash","-c","cd /opt/app/osaaf/local && /opt/app/aaf_config/bin/agent.sh place aaf@aaf.osaaf.org aaf-hello "]
          env:
            - name: "AAF_ENV"
              value: "{{ .Values.cadi.aaf_env }}"
            - name: "AAF_FQDN"
              value: "aaf-locate.{{ .Release.Namespace }}"
            - name: "APP_FQDN"
              value: "{{ .Values.cadi.fqdn }}"
            - name: "APP_FQI"
              value: "{{ .Values.cadi.fqi }}"
            - name: "LATITUDE"
              value: "{{ .Values.cadi.cadi_latitude }}"
            - name: "LONGITUDE"
              value: "{{ .Values.cadi.cadi_longitude }}"
            - name: "DEPLOY_FQI"
              value: "deployer@people.osaaf.org"
            - name: "DEPLOY_PASSWORD"
              value: "demo123456!"
            - name: "aaf_locator_container"
              value: "helm"
            - name: "aaf_locator_port"
              value: "{{ .Values.cadi.port }}"
            - name: "aaf_locator_fqdn.helm"
              value: "{{ .Values.cadi.fqdn }}.{{.Release.Namespace}}"
            - name: "aaf_locator_public_hostname"
              value: "{{ .Values.cadi.public_fqdn }}"
            - name: "aaf_locator_public_port"
              value: "{{ .Values.cadi.public_port }}"
            - name: "aaf_locator_container_ns"
              value: "{{ .Release.Namespace }}"
            - name: "aaf_locator_name"
              value: "{{.Values.cadi.app_ns}}.hello"
            - name: "aaf_locator_name.helm"
              value: "{{ .Release.Namespace}}.{{.Values.cadi.app_ns}}.hello"

###
### AAF-HELLO
###
      containers:
      - name: aaf-hello
        image: {{ .Values.image.repository }}onap/aaf/aaf_hello:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","-c","cd /opt/app/aaf && exec bin/hello"]
        volumeMounts:
        -  mountPath: "/opt/app/osaaf/local"
           name: aaf-hello-vol
        ports:
        - name: aaf-hello
          protocol: TCP
          containerPort: 8130
