#-------------------------------------------------------------------------------
# ============LICENSE_START====================================================
# * org.onap.aaf
# * ===========================================================================
# * Copyright © 2017 AT&T Intellectual Property. All rights reserved.
# * ===========================================================================
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# * 
#  *      http://www.apache.org/licenses/LICENSE-2.0
# * 
#  * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# * ============LICENSE_END====================================================
# *
# *
#-------------------------------------------------------------------------------
version: '2'
services:
  aaf_container:
    image: onap/aaf/authz-service:1.0.1-SNAPSHOT
    ports:
      - "8101:8101"

    links:
      - cassandra_container
    volumes:
    # - ./authAPI.props:/opt/app/aaf/authz-service/2.0.15/etc/authAPI.props
      - ./wait_for_host_port.sh:/tmp/wait_for_host_port.sh
      - ./data2:/data
    # - ./runaafcli.sh:/opt/app/aaf/authz-service/2.0.15/runaafcli.sh
    #  - ./com.osaaf.common.props:/opt/app/aaf/authz-service/2.0.15/etc/com.osaaf.common.props
    # - ./cadi-core-1.3.0.jar:/opt/app/aaf/authz-service/2.0.15/lib/cadi-core-1.3.0.jar
    #  - ./cadi-aaf-1.3.0.jar:/opt/app/aaf/authz-service/2.0.15/lib/cadi-aaf-1.3.0.jar
    # - ./cadi-client-1.3.0.jar:/opt/app/aaf/authz-service/2.0.15/lib/cadi-client-1.3.0.jar
    # - ./authz-service-2.0.15.jar:/opt/app/aaf/authz-service/2.0.15/lib/authz-service-2.0.15.jar
    #  - ./dme2-3.1.200.jar:/opt/app/aaf/authz-service/2.0.15/lib/dme2-3.1.200.jar
    entrypoint: ["bash", "-c", "/tmp/wait_for_host_port.sh cassandra_container 9042; sleep 20; /bin/sh -c ./startup.sh"]
    environment:
      - CASSANDRA_CLUSTER=cassandra_container
    

  cassandra_container:
    image: cassandra:2.1.16
    ports:
      - "7000:7000"
      - "7001:7001"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - ./data:/data
      - ./wait_for_host_port.sh:/tmp/wait_for_host_port.sh
    entrypoint: ["bash", "-c", "(/tmp/wait_for_host_port.sh localhost 9042 cqlsh --file /data/init.cql -u cassandra -p cassandra localhost; cqlsh --file /data/ecomp.cql -u cassandra -p cassandra localhost) & (/docker-entrypoint.sh cassandra -f)"]
